image:
  file: .gitpod.Dockerfile
tasks:
  - name: start DB
    init: echo 'init script' # runs during prebuild
    before: gp sync-await multispace
    command: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'p@ssw0rd1';"
